### ISSUE TITLE
Cannot see it in ChocolateBar

### ISSUE THREAD

**Issue by kkrzyzak** [Septh/WoW-Broker_Cash#1]
Hi,

I installed the addon via Twitch app, but it neither shows in my ChocolateBar nor I can use commmand /bcash (nor /brokercash). 
I can see addon in the list of addons available from login screen though. 
Also it has its folder in \interface\AddOns\ as well as a file WTF\Account\<name>\SavedVariables\Broker_Cash.lua (wth only one row Broker_CashDB=nil)

I am not sure why I cannot see it, Could you help me please?

**Comment by Septh** [comment]
If the Broker_Cash.lua file does exist in your WTF folder, then the addon has been correctly loaded by the game. Did you check your ChocolateBar settings? Do your see the addon in the list of loaded plugins?

**Comment by kkrzyzak** [comment]
No, I don't see it in ChockolateBar settings (list of plugins). 
This is weird as I can see it on the list of addons on character login screen, but it looks like it is not recognized as plugin by ChockolateBar neither it responses to /bcash /brokercash commands.

**Comment by Septh** [comment]
Ok, I got it - was a problem with fresh installs :/ 

I just uploaded v1.4.3 to Curse, the Twitch client should allow you to update very soon (please note I did release 1.4.2 this very morning, so make sure you actually update to 1.4.3).

Many thanks for pointing out.

**Comment by kkrzyzak** [comment]
It is working. Thanks!
