### ISSUE TITLE
LUA error for a while now

### ISSUE THREAD

**Issue by CTauthor** [Septh/WoW-Broker_Cash#11]
Receive following LUA error EVERY TIME my cursor passes over Broker Cash:

Message: ...\AddOns\Broker_Cash\Libs\LibQTip-1.0\LibQTip-1.0.lua:543: attempt to call method 'GetBackdrop' (a nil value)
Time: Fri Nov 26 15:23:30 2021
Count: 1
Stack: ...\AddOns\Broker_Cash\Libs\LibQTip-1.0\LibQTip-1.0.lua:543: attempt to call method 'GetBackdrop' (a nil value)
[string "@Interface\AddOns\Broker_Cash\Libs\LibQTip-1.0\LibQTip-1.0.lua"]:543: in function <...\AddOns\Broker_Cash\Libs\LibQTip-1.0\LibQTip-1.0.lua:539>
[string "@Interface\AddOns\Broker_Cash\Libs\LibQTip-1.0\LibQTip-1.0.lua"]:132: in function `Acquire'
[string "@Interface\AddOns\Broker_Cash\Broker_Cash.lua"]:730: in function `ShowMainTooltip'
[string "@Interface\AddOns\Broker_Cash\Broker_Cash.lua"]:966: in function `OnEnter'
[string "@Interface\AddOns\Bazooka\Bazooka.lua"]:1583: in function `showTip'
[string "@Interface\AddOns\Bazooka\Bazooka.lua"]:1388: in function <Interface\AddOns\Bazooka\Bazooka.lua:1379>

Locals: tooltip = <unnamed> {
 0 = <userdata>
 scrollChild = <unnamed> {
 }
 scrollFrame = <unnamed> {
 }
}
key = "Broker_Cash_MainTooltip"
(*temporary) = nil
(*temporary) = GameTooltip {
 0 = <userdata>
 textLeft1Font = "GameTooltipHeaderText"
 ItemTooltip = <unnamed> {
 }
 SetHyperlink = <function> defined =[C]:-1
 SetGuildBankItem = <function> defined =[C]:-1
 updateTooltipTimer = 0.100000
 Hide = <function> defined =[C]:-1
 TextRight1 = GameTooltipTextRight1 {
 }
 hasMoney = 1
 ClearLines = <function> defined =[C]:-1
 SetSocketGem = <function> defined =[C]:-1
 SetUnitBuff = <function> defined =[C]:-1
 TopOverlay = <unnamed> {
 }
 SetUnitDebuff = <function> defined =[C]:-1
 comparing = false
 SetLootItem = <function> defined =[C]:-1
 SetQuestItem = <function> defined @Interface\AddOns\Altoholic\Services\Tooltip.lua:546
 TextLeft1 = GameTooltipTextLeft1 {
 }
 waitingForData = false
 SetTrainerService = <function> defined =[C]:-1
 numMoneyFrames = 1
 SetInboxItem = <function> defined =[C]:-1
 SetExistingSocketGem = <function> defined =[C]:-1
 SetRecipeReagentItem = <function> defined @Interface\AddOns\Altoholic\Services\Tooltip.lua:546
 SetBuybackItem = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 SetCurrencyToken = <function> defined @Interface\AddOns\Altoholic\Services\Tooltip.lua:546
 SetMerchantItem = <function> defined =[C]:-1
 SetQuestLogItem = <function> defined @Interface\AddOns\Altoholic\Services\Tooltip.lua:546
 SetBackpackToken = <function> defined =[C]:-1
 BottomOverlay = <unnamed> {
 }
 SetMerchantCostItem = <function> defined =[C]:-1
 SetTradePlayerItem = <function> defined =[C]:-1
 textRight1Font = "GameTooltipHeaderText"
 SetSendMailItem = <function> defined =[C]:-1
 Show = <function> defined =[C]:-1
 NineSlice = <unnamed> {
 }
 textLeft2Font = "GameTooltipText"
 SetLootRollItem = <function> defined =[C]:-1
 TextRight2 = GameTooltipTextRight2 {
 }
 TextLeft2 = GameTooltipTextLeft2 {
 }
 SetUnitAura = <function> defined =[C]:-1
 layoutType = "TooltipDefaultLayout"
 CIMI_tooltipWritten = false
 SetBagItem = <function> defined =[C]:-1
 needsReset = true
 SetTradeTargetItem = <function> defined =[C]:-1
 SetInventoryItem = <function> defined =[C]:-1
 textRight2Font = "GameTooltipText"
 SetRecipeResultItem = <function> defined @Interface\AddOns\Altoholic\Services\Tooltip.lua:546
}
(*temporary) = "attempt to call method 'GetBackdrop' (a nil value)"
GameTooltip = GameTooltip {
 0 = <userdata>
 textLeft1Font = "GameTooltipHeaderText"
 ItemTooltip = <unnamed> {
 }
 SetHyperlink = <function> defined =[C]:-1
 SetGuildBankItem = <function> defined =[C]:-1
 updateTooltipTimer = 0.100000
 Hide = <function> defined =[C]:-1
 TextRight1 = GameTooltipTextRight1 {
 }
 hasMoney = 1
 ClearLines = <function> defined =[C]:-1
 SetSocketGem = <function> defined =[C]:-1
 SetUnitBuff = <function> defined =[C]:-1
 TopOverlay = <unnamed> {
 }
 SetUnitDebuff = <function> defined =[C]:-1
 comparing = false
 SetLootItem = <function> defined =[C]:-1
 SetQuestItem = <function> defined @Interface\AddOns\Altoholic\Services\Tooltip.lua:546
 TextLeft1

-AND-

Message: ...\AddOns\Broker_Cash\Libs\LibQTip-1.0\LibQTip-1.0.lua:543: attempt to call method 'GetBackdrop' (a nil value)
Time: Fri Nov 26 15:23:37 2021
Count: 2
Stack: ...\AddOns\Broker_Cash\Libs\LibQTip-1.0\LibQTip-1.0.lua:543: attempt to call method 'GetBackdrop' (a nil value)
[string "@Interface\AddOns\Broker_Cash\Libs\LibQTip-1.0\LibQTip-1.0.lua"]:543: in function <...\AddOns\Broker_Cash\Libs\LibQTip-1.0\LibQTip-1.0.lua:539>
[string "@Interface\AddOns\Broker_Cash\Libs\LibQTip-1.0\LibQTip-1.0.lua"]:132: in function `Acquire'
[string "@Interface\AddOns\Broker_Cash\Broker_Cash.lua"]:730: in function `ShowMainTooltip'
[string "@Interface\AddOns\Broker_Cash\Broker_Cash.lua"]:966: in function `OnEnter'
[string "@Interface\AddOns\Bazooka\Bazooka.lua"]:1583: in function `showTip'
[string "@Interface\AddOns\Bazooka\Bazooka.lua"]:2170: in function `?'
[string "@Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...\AddOns\DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

**Comment by CTauthor** [comment]
Still waiting for ANY feedback!

**Comment by Septh** [comment]
Apologies, I don't play WoW anymore so there is not much I can do.

My understanding is the problem comes from the LibQTip-1.0 library bundled with BrokerCash. You may try to download and install the latest version which is said to fix this problem : https://www.curseforge.com/wow/addons/libqtip-1-0/files

Once installed, it should replace the outdated version in BrokerCash.

Please tell me if this worked for you.

**Comment by Septh** [comment]
As a side note, it may also be worth installing the lastest Ace3 : https://www.wowace.com/projects/ace3/files

**Comment by GeoRam2016** [comment]
> Apologies, I don't play WoW anymore so there is not much I can do.
> 
> My understanding is the problem comes from the LibQTip-1.0 library bundled with BrokerCash. You may try to download and install the latest version which is said to fix this problem : https://www.curseforge.com/wow/addons/libqtip-1-0/files
> 
> Once installed, it should replace the outdated version in BrokerCash.
> 
> Please tell me if this worked for you.

Hi
It´s work fine in Patch 9.1.5 and 9.2
thx for the link
