### ISSUE TITLE
Bug 10.0.

### ISSUE THREAD

**Issue by GeoRam2016** [Septh/WoW-Broker_Cash#14]
Hi

Bug Found

 

3x .../AddOns/Broker_Cash/libs/LibQTip-1.0-48/LibQTip-1.0.lua:543: attempt to call method 'GetBackdrop' (a nil value)
[string "@Interface/AddOns/Broker_Cash/libs/LibQTip-1.0-48/LibQTip-1.0.lua"]:543: in function <.../AddOns/Broker_Cash/libs/LibQTip-1.0/LibQTip-1.0.lua:539>
[string "@Interface/AddOns/Broker_Cash/libs/LibQTip-1.0-48/LibQTip-1.0.lua"]:132: in function `Acquire'
[string "@Interface/AddOns/Broker_Cash/Broker_Cash.lua"]:829: in function `ShowMainTooltip'
[string "@Interface/AddOns/Broker_Cash/Broker_Cash.lua"]:1101: in function `OnEnter'
[string "@Interface/AddOns/Bazooka/Bazooka.lua"]:1582: in function `showTip'
[string "@Interface/AddOns/Bazooka/Bazooka.lua"]:1387: in function <Interface/AddOns/Bazooka/Bazooka.lua:1378>

Locals:
tooltip = Frame {
0 = <userdata>
scrollChild = Frame {
}
scrollFrame = ScrollFrame {
}
}
key = "Broker_Cash_MainTooltip"
(*temporary) = nil
(*temporary) = GameTooltip {
0 = <userdata>
textLeft1Font = "GameTooltipHeaderText"
ItemTooltip = Frame {
}
SetHyperlink = <function> defined =[C]:-1
SetGuildBankItem = <function> defined =[C]:-1
updateTooltipTimer = 0.019000
SetVoidDepositItem = <function> defined =[C]:-1
Hide = <function> defined =[C]:-1
hasMoney = 1
TextRight1 = GameTooltipTextRight1 {
}
SetLootRollItem = <function> defined =[C]:-1
ClearLines = <function> defined =[C]:-1
SetSocketGem = <function> defined =[C]:-1
SetVoidWithdrawalItem = <function> defined =[C]:-1
TopOverlay = Texture {
}
comparing = false
SetExistingSocketGem = <function> defined =[C]:-1
SetItemByID = <function> defined =[C]:-1
SetLootItem = <function> defined =[C]:-1
SetQuestItem = <function> defined =[C]:-1
SetTradeTargetItem = <function> defined =[C]:-1
waitingForData = false
SetTrainerService = <function> defined =[C]:-1
numMoneyFrames = 1
SetVoidItem = <function> defined =[C]:-1
SetHeirloomByItemID = <function> defined =[C]:-1
SetRecipeReagentItem = <function> defined @Interface/AddOns/Altoholic/Services/Tooltip.lua:616
SetBuybackItem = <function> defined =[C]:-1
shoppingTooltips = <table> {
}
SetWeeklyReward = <function> defined =[C]:-1
SetMerchantItem = <function> defined =[C]:-1
SetQuestLogItem = <function> defined =[C]:-1
SetItemKey = <function> defined =[C]:-1
BottomOverlay = Texture {
}
SetInventoryItem = <function> defined =[C]:-1
SetTradePlayerItem = <function> defined =[C]:-1
textRight1Font = "GameTooltipHeaderText"
SetSendMailItem = <function> defined =[C]:-1
SetCurrencyToken = <function> defined @Interface/AddOns/Altoholic/Services/Tooltip.lua:616
NineSlice = Frame {
}
textLeft2Font = "GameTooltipText"
Show = <function> defined =[C]:-1
TextRight2 = GameTooltipTextRight2 {
}
TextLeft2 = GameTooltipTextLeft2 {
}
SetInboxItem = <function> defined =[C]:-1
SetBagItem = <function> defined =[C]:-1
needsReset = true
layoutType = "TooltipDefaultLayout"
TextLeft1 = GameTooltipTextLeft1 {
}
textRight2Font = "GameTooltipText"
SetRecipeResultItem = <function> defined =[C]:-1
}
(*temporary) = "attempt to call method 'GetBackdrop' (a nil value)"
GameTooltip = GameTooltip {
0 = <userdata>
textLeft1Font = "GameTooltipHeaderText"
ItemTooltip = Frame {
}
SetHyperlink = <function> defined =[C]:-1
SetGuildBankItem = <function> defined =[C]:-1
updateTooltipTimer = 0.019000
SetVoidDepositItem = <function> defined =[C]:-1
Hide = <function> defined =[C]:-1
hasMoney = 1
TextRight1 = GameTooltipTextRight1 {
}
SetLootRollItem = <function> defined =[C]:-1
ClearLines = <function> defined =[C]:-1
SetSocketGem = <function> defined =[C]:-1
SetVoidWithdrawalItem = <function> defined =[C]:-1
TopOverlay = Texture {
}
comparing = false
SetExistingSocketGem = <function> defined =[C]:-1
SetItemByID = <function> defined =[C]:-1
SetLootItem = <function> defined =[C]:-1
SetQuestItem = <function> defined =[C]:-1
SetTradeTargetItem = <function> defined =[C]:-1
waitingForData = false
SetTrainerService = <function> defined =[C]:-1
numMoneyFrames = 1
SetVoidItem = <function> defined =[C]:-1
SetHeirloomByItemID = <function> defined =[C]:-1
SetRecipeReagentItem = <function> defined @Interface/AddOns/Altoholic/Services/Tooltip.lua:616
SetBuybackItem = <function> defined =[C]:-1
shoppingTooltips = <table> {
}
SetWeeklyReward = <function> defined =[C]:-1
SetMerchantItem = <function> defined =[C]:-1
SetQuestLogItem = <function> defined =[C]:-1
SetItemKey = <function> defined =[C]:-1
BottomOverlay = Texture {
}
SetInventoryItem = <function> defined =[C]:-1
SetTradePlayerItem = <function> defined =[C]:-1
textRight1Font = "GameTooltipHeaderText"
SetSendMailItem = <function> defined =[C]:-1
SetCurrencyToken = <function> defined @Interface/AddOns/Altoholic/Services/Tooltip.lua:616
NineSlice = Frame {
}
textLeft2Font = "GameTooltipText"
Show = <function> defined =[C]:-1
TextRig

**Comment by GeoRam2016** [comment]
I have Copied this in Lib Ordner, the works fine. Pls Fix it, thx
https://www.curseforge.com/wow/addons/libqtip-1-0/files

**Comment by neun0eil** [comment]
Hi,
Nice find, I use ElvUI and this error is not thrown with it.
