### ISSUE TITLE
show RealmTotal in LDB

### ISSUE THREAD

**Issue by Daeveren** [Septh/WoW-Broker_Cash#5]
It would be awesome to let us chose to show RealmTotal gold in the broker display - preferably add some display options there too for gold display - condensed (123 12 11 - color coded), short (123.1g), full (123g 12s 11c), coins (just like full but with gold/silver/copper icons instead of g/s/c/ letters).

**Comment by Septh** [comment]
Well, that could probably be done in a future release. I'll keep your suggestion in mind, thanks.
