### ISSUE TITLE
CurseForge description states what addons are required. Twitch App description does not.

### ISSUE THREAD

**Issue by Jaldy** [Septh/WoW-Broker_Cash#6]
No huge issue, but the Twitch app description does not say that a library is required.  I googled your addon and on the CurseForge description, it says what is required.  Just a heads up. :)

**Comment by Septh** [comment]
Yep, my bad. I'll correct this in the next release. Thanks for the report!

**Comment by Jaldy** [comment]
Love the add-on! It's great for grinding trips to see how much you make.

**Comment by Septh** [comment]
The latest version is out and the readme has been updated. Happy grinding! ;)
