### ISSUE TITLE
v2.1.2 - Not processed by Twitch client / duplicate file nam?

### ISSUE THREAD

**Issue by ghost** [Septh/WoW-Broker_Cash#7]
Latest version cannot be processed using Twitch Client. Is it possible a duplicate file name causes this issue?

This is what I have found in the archive:
CHANGELOG.md
Changelog.md

**Comment by ghost** [comment]
Typo in title

**Comment by Septh** [comment]
Thanks for the report.

I have uploaded v2.1.3 which the Twitch client should process correctly, please let me know if this works for you - it does for me :)

**Comment by ghost** [comment]
Thanks for the swift response.

 

The package issue is solved, but after updating, a bunch of LUA errors occurs. Have submitted a new issue for this.

 

Gesendet: Donnerstag, 10. Oktober 2019 um 12:01 Uhr
Von: "Stephan Schreiber" <notifications@github.com>
An: Septh/WoW-Broker_Cash <WoW-Broker_Cash@noreply.github.com>
Cc: Cyrix72 <webanmeldung@gmx.org>, Author <author@noreply.github.com>
Betreff: Re: [Septh/WoW-Broker_Cash] v2.1.2 - Not processed by Twitch client / duplicate file nam? (#7)


Thanks for the report.

I have uploaded v2.1.3 which the Twitch client should process correctly, please let me know if this works for you - it does for me :)

**Comment by Septh** [comment]
I'll close this issue then, moving next to other one :)

Thanks again.
