### ISSUE TITLE
2.1.3 LUA errors - no function

### ISSUE THREAD

**Issue by ghost** [Septh/WoW-Broker_Cash#8]
After updating, I receive a bunch of LUA errors:
**1.**
1x Broker_Cash\Libs\LibQTip-1.0\LibQTip-1.0.lua:163: unexpected symbol near ']'

Locals:

2.
1x Broker_Cash\Broker_Cash-2.1.3.lua:20: Cannot find a library instance of "LibQTip-1.0".
[C]: in function `error'
...ator\Libs\LibItemUpgradeInfo-1.0-30\LibStub\LibStub.lua:38: in function `LibStub'
Broker_Cash\Broker_Cash-2.1.3.lua:20: in main chunk

Locals:
(*temporary) = "Cannot find a library instance of "LibQTip-1.0"."

3.
3x Broker_Cash\Libs\LibQTip-1.0\LibQTip-1.0-46.lua:163: unexpected symbol near ']'

**4.**
3x (null)

**Comment by Septh** [comment]
Looks like the packager has some difficulties with LibQTip :(

I don't have much time right now to investigate into this so for now I'll just monkey patch the faulty file as an emergency fix. A new release should be available very quickly via Twitch.

Thanks for the report; I'll leave this issue open as a reminder until I find a long term fix.
