### ISSUE TITLE
Lua Error Pre-Patch 9.0.1

### ISSUE THREAD

**Issue by GeoRam2016** [Septh/WoW-Broker_Cash#9]
Hi
pls fix it

1x Broker_Cash\Libs\LibQTip-1.0\LibQTip-1.0-46.lua:519: attempt to call method 'SetBackdrop' (a nil value)
[string "@Broker_Cash\Libs\LibQTip-1.0\LibQTip-1.0-46.lua"]:519: in function <Broker_Cash\Libs\LibQTip-1.0\LibQTip-1.0.lua:513>
[string "@Broker_Cash\Libs\LibQTip-1.0\LibQTip-1.0-46.lua"]:126: in function `Acquire'
[string "@Broker_Cash\Broker_Cash-2.1.4.lua"]:716: in function `ShowMainTooltip'
[string "@Broker_Cash\Broker_Cash-2.1.4.lua"]:952: in function `OnEnter'
[string "@Bazooka\Bazooka-r318.lua"]:1583: in function `showTip'
[string "@Bazooka\Bazooka-r318.lua"]:1388: in function <Bazooka\Bazooka.lua:1379>

Locals:
tooltip = <unnamed> {
 0 = <userdata>
 scrollChild = <unnamed> {
 }
 scrollFrame = <unnamed> {
 }
}
key = "Broker_Cash_MainTooltip"
backdrop = <table> {
 backdropColor = <table> {
 }
 edgeSize = 16
 tileEdge = true
 backdropBorderColor = <table> {
 }
 tileSize = 16
 edgeFile = "Interface/Tooltips/UI-Tooltip-Border"
 tile = true
 bgFile = "Interface/Tooltips/UI-Tooltip-Background"
 insets = <table> {
 }
}
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
 scrollChild = <unnamed> {
 }
 scrollFrame = <unnamed> {
 }
}
(*temporary) = <table> {
 backdropColor = <table> {
 }
 edgeSize = 16
 tileEdge = true
 backdropBorderColor = <table> {
 }
 tileSize = 16
 edgeFile = "Interface/Tooltips/UI-Tooltip-Border"
 tile = true
 bgFile = "Interface/Tooltips/UI-Tooltip-Background"
 insets = <table> {
 }
}
(*temporary) = "attempt to call method 'SetBackdrop' (a nil value)"
GameTooltip = GameTooltip {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:205
 SetExistingSocketGem = <function> defined =[C]:-1
 SetHyperlink = <function> defined =[C]:-1
 RightEdge = <unnamed> {
 }
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:335
 SetLootItem = <function> defined =[C]:-1
 numMoneyFrames = 1
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 SetMerchantItem = <function> defined =[C]:-1
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:267
 TopRightCorner = <unnamed> {
 }
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:241
 updateTooltip = 0.100000
 SetInventoryItem = <function> defined =[C]:-1
 TopEdge = <unnamed> {
 }
 SetLootRollItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 BottomRightCorner = <unnamed> {
 }
 SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:452
 LeftEdge = <unnamed> {
 }
 textLeft1Font = "GameTooltipHeaderText"
 SetCurrencyToken = <function> defined @Altoholic\Tooltip.lua:700
 SetGuildBankItem = <function> defined =[C]:-1
 hasMoney = 1
 TopLeftCorner = <unnamed> {
 }
 Hide = <function> defined =[C]:-1
 TextRight1 = GameTooltipTextRight1 {
 }
 ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:347
 SetBackdrop = <function> defined @SharedXML\Backdrop.lua:382
 TopOverlay = <unnamed> {
 }
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:462
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:400
 SetUnitDebuff = <function> defined =[C]:-1
 SetHeirloomByItemID = <function> defined =[C]:-1
 comparing = false
 SetQuestItem = <function> defined =[C]:-1
 __tamedCounts = false
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:319
 SetTrainerService = <function> defined =[C]:-1
 SetAction = <function> defined =[C]:-1
 SetUnitBuff = <function> defined =[C]:-1
 BottomLeftCorner = <unnamed> {
 }
 SetInboxItem = <function> defined =[C]:-1
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:443
 TextLeft1 = GameTooltipTextLeft1 {
 }
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:331
 BottomEdge = <unnamed> {
 }
 Center = <unnamed> {
 }
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:235
 SetTradeTargetItem = <function> defined =[C]:-1
 ItemTooltip = <unnamed> {
 }
 SetTradePlayerItem = <function> defined =[C]:-1
 textRight1Font = "GameTooltipHeaderText"
 SetSendMailItem = <function> defined =[C]:-1
 SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:475
 SetItemByID = <function> defined =[C]:-1
 textLeft2Font = "GameTooltipText"
 textRight2Font = "GameTooltipText"
 TextRight2 = GameTooltipTextRight2 {
 }
 TextLeft2 = GameTooltipTextLeft2 {
 }
 SetUnitAura = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 backdropInfo = <table> {
 }
 SetItemKey = <function> defined =[C]:-1
 needsReset = true
 SetupPieceVisuals = <function> defined @SharedXML\Backdrop.lua:299
 SetQuestLogItem = <function

**Comment by GeoRam2016** [comment]
2x Broker_Cash\Libs\LibQTip-1.0\LibQTip-1.0-46.lua:519: attempt to call method 'SetBackdrop' (a nil value)
[string "@Broker_Cash\Libs\LibQTip-1.0\LibQTip-1.0-46.lua"]:519: in function <Broker_Cash\Libs\LibQTip-1.0\LibQTip-1.0.lua:513>
[string "@Broker_Cash\Libs\LibQTip-1.0\LibQTip-1.0-46.lua"]:126: in function `Acquire'
[string "@Broker_Cash\Broker_Cash-2.1.4.lua"]:716: in function `ShowMainTooltip'
[string "@Broker_Cash\Broker_Cash-2.1.4.lua"]:952: in function `OnEnter'
[string "@Bazooka\Bazooka-r318.lua"]:1583: in function `showTip'
[string "@Bazooka\Bazooka-r318.lua"]:1388: in function <Bazooka\Bazooka.lua:1379>

Locals:
tooltip = <unnamed> {
 0 = <userdata>
 scrollChild = <unnamed> {
 }
 scrollFrame = <unnamed> {
 }
}
key = "Broker_Cash_MainTooltip"
backdrop = <table> {
 backdropColor = <table> {
 }
 edgeSize = 16
 tileEdge = true
 backdropBorderColor = <table> {
 }
 tileSize = 16
 edgeFile = "Interface/Tooltips/UI-Tooltip-Border"
 tile = true
 bgFile = "Interface/Tooltips/UI-Tooltip-Background"
 insets = <table> {
 }
}
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
 scrollChild = <unnamed> {
 }
 scrollFrame = <unnamed> {
 }
}
(*temporary) = <table> {
 backdropColor = <table> {
 }
 edgeSize = 16
 tileEdge = true
 backdropBorderColor = <table> {
 }
 tileSize = 16
 edgeFile = "Interface/Tooltips/UI-Tooltip-Border"
 tile = true
 bgFile = "Interface/Tooltips/UI-Tooltip-Background"
 insets = <table> {
 }
}
(*temporary) = "attempt to call method 'SetBackdrop' (a nil value)"
GameTooltip = GameTooltip {
 0 = <userdata>
 OnBackdropLoaded = <function> defined @SharedXML\Backdrop.lua:205
 SetExistingSocketGem = <function> defined =[C]:-1
 SetHyperlink = <function> defined =[C]:-1
 RightEdge = <unnamed> {
 }
 ClearBackdrop = <function> defined @SharedXML\Backdrop.lua:335
 SetLootItem = <function> defined =[C]:-1
 SetRecipeReagentItem = <function> defined =[C]:-1
 SetBuybackItem = <function> defined =[C]:-1
 SetMerchantItem = <function> defined =[C]:-1
 SetupTextureCoordinates = <function> defined @SharedXML\Backdrop.lua:267
 TopRightCorner = <unnamed> {
 }
 GetEdgeSize = <function> defined @SharedXML\Backdrop.lua:241
 updateTooltip = 0.150000
 SetInventoryItem = <function> defined =[C]:-1
 TopEdge = <unnamed> {
 }
 SetLootRollItem = <function> defined =[C]:-1
 SetBagItem = <function> defined =[C]:-1
 BottomRightCorner = <unnamed> {
 }
 SetBackdropColor = <function> defined @SharedXML\Backdrop.lua:452
 LeftEdge = <unnamed> {
 }
 textLeft1Font = "GameTooltipHeaderText"
 SetCurrencyToken = <function> defined @Altoholic\Tooltip.lua:700
 SetGuildBankItem = <function> defined =[C]:-1
 TopLeftCorner = <unnamed> {
 }
 Hide = <function> defined =[C]:-1
 TextRight1 = GameTooltipTextRight1 {
 }
 ApplyBackdrop = <function> defined @SharedXML\Backdrop.lua:347
 SetBackdrop = <function> defined @SharedXML\Backdrop.lua:382
 TopOverlay = <unnamed> {
 }
 GetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:462
 GetBackdrop = <function> defined @SharedXML\Backdrop.lua:400
 SetUnitDebuff = <function> defined =[C]:-1
 SetHeirloomByItemID = <function> defined =[C]:-1
 SetAction = <function> defined =[C]:-1
 SetQuestItem = <function> defined =[C]:-1
 comparing = false
 SetBorderBlendMode = <function> defined @SharedXML\Backdrop.lua:319
 SetTrainerService = <function> defined =[C]:-1
 __tamedCounts = false
 SetUnitBuff = <function> defined =[C]:-1
 BottomLeftCorner = <unnamed> {
 }
 SetInboxItem = <function> defined =[C]:-1
 GetBackdropColor = <function> defined @SharedXML\Backdrop.lua:443
 TextLeft1 = GameTooltipTextLeft1 {
 }
 HasBackdropInfo = <function> defined @SharedXML\Backdrop.lua:331
 BottomEdge = <unnamed> {
 }
 Center = <unnamed> {
 }
 OnBackdropSizeChanged = <function> defined @SharedXML\Backdrop.lua:235
 SetTradeTargetItem = <function> defined =[C]:-1
 ItemTooltip = <unnamed> {
 }
 SetTradePlayerItem = <function> defined =[C]:-1
 textRight1Font = "GameTooltipHeaderText"
 SetSendMailItem = <function> defined =[C]:-1
 SetBackdropBorderColor = <function> defined @SharedXML\Backdrop.lua:475
 SetItemByID = <function> defined =[C]:-1
 textLeft2Font = "GameTooltipText"
 textRight2Font = "GameTooltipText"
 TextRight2 = GameTooltipTextRight2 {
 }
 TextLeft2 = GameTooltipTextLeft2 {
 }
 SetUnitAura = <function> defined =[C]:-1
 shoppingTooltips = <table> {
 }
 backdropInfo = <table> {
 }
 SetItemKey = <function> defined =[C]:-1
 needsReset = true
 SetupPieceVisuals = <function> defined @SharedXML\Backdrop.lua:299
 SetQuestLogItem = <function> defined =[C]:-1
 BottomOverlay =

**Comment by Septh** [comment]
Hi!

Thanks for reporting.

I updated the addon with the latest Ace3 and LibQTip libraries, it should work just fine again. However, I can't test myself because I don't play WoW anymore. Could you please check if everything is OK and update this issue acorgindly? Thanks in advance.

**Comment by GeoRam2016** [comment]
Thx
Works fine

**Comment by Septh** [comment]
Great! Happy gaming, then.
